[package]
name = "pesde-registry"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.5.1"
actix-cors = "0.7.0"
actix-web-httpauth = "0.8.1"
actix-multipart = "0.6.1"
actix-multipart-derive = "0.6.1"
dotenvy = "0.15.7"
reqwest = { version = "0.11.24", features = ["json", "blocking"] }
rusty-s3 = "0.5.0"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
serde_yaml = "0.9.32"
flate2 = "1.0.28"
tar = "0.4.40"
pesde = { path = ".." }
semver = "1.0.22"
git2 = "0.18.2"
thiserror = "1.0.57"
tantivy = "0.21.1"
log = "0.4.21"
pretty_env_logger = "0.5.0"
sentry = "0.32.2"
sentry-log = "0.32.2"
sentry-actix = "0.32.2"